apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.api.name }}
  annotations:
    kubernetes.io/change-cause: "Deployed image {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"

spec:
  replicas: {{ .Values.api.replicaCount }}

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: {{ .Values.api.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}

    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.api.containerPort }}

          envFrom:
            - configMapRef:
                name: redis-cm

            - secretRef:
                name: redis-secret

          startupProbe:
            httpGet:
              path: {{ .Values.api.probes.startup.path }}
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: {{ .Values.api.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.readiness.path }}
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.liveness.path }}
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}

          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
